/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_projeto;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author pcate
 */
public class Form_usuario_login extends javax.swing.JFrame {

    /**
     * Creates new form Form_usuario_login
     */
    public Form_usuario_login() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_login = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel_titulo_usuario = new javax.swing.JLabel();
        jLabel_registro = new javax.swing.JLabel();
        jLabel_direciona_farmaceutico = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_Minimize1 = new javax.swing.JLabel();
        jLabel_Close2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel_login.setText("Login");

        jLabel_password.setText("Senha");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel_titulo_usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_titulo_usuario.setText("Seja Bem vindo ao FarmaZYX");

        jLabel_registro.setText("Ainda não tem login? Faça um cadastro agora mesmo!");
        jLabel_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registroMouseClicked(evt);
            }
        });

        jLabel_direciona_farmaceutico.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_direciona_farmaceutico.setText("Você farmaceutico faça login na nossa plataforma voltada a você!");
        jLabel_direciona_farmaceutico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_direciona_farmaceuticoMouseClicked(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_Minimize1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Minimize1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Minimize1.setText("-");
        jLabel_Minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Minimize1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Minimize1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Minimize1MouseExited(evt);
            }
        });

        jLabel_Close2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Close2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Close2.setText("x");
        jLabel_Close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Close2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Close2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Close2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel_password)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel_login)
                                        .addGap(20, 20, 20)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel_direciona_farmaceutico)
                            .addComponent(jLabel_registro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel_titulo_usuario)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Minimize1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel_Close2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Minimize1)
                    .addComponent(jLabel_Close2))
                .addGap(15, 15, 15)
                .addComponent(jLabel_titulo_usuario)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_login)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_password)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(19, 19, 19)
                .addComponent(jLabel_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel_direciona_farmaceutico)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel_direciona_farmaceuticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_direciona_farmaceuticoMouseClicked
        Form_usuario_farmacia  uf = new Form_usuario_farmacia();
        uf.setVisible(true);
        uf.pack();
        uf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        /* Register_form rf = new Register_form();
        rf.setVisible(true);
        rf.pack();
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        */
    }//GEN-LAST:event_jLabel_direciona_farmaceuticoMouseClicked

    private void jLabel_Minimize1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Minimize1MouseEntered
            Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_Minimize1.setBorder(label_border);
        jLabel_Minimize1.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_Minimize1MouseEntered

    private void jLabel_Minimize1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Minimize1MouseExited
         Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Minimize1.setBorder(label_border);
        jLabel_Minimize1.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_Minimize1MouseExited

    private void jLabel_Minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Minimize1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_Minimize1MouseClicked

    private void jLabel_Close2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Close2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_Close2MouseClicked

    private void jLabel_Close2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Close2MouseEntered
         Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_Close2.setBorder(label_border);
        jLabel_Close2.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_Close2MouseEntered

    private void jLabel_Close2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Close2MouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Close2.setBorder(label_border);
        jLabel_Close2.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_Close2MouseExited

    private void jLabel_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registroMouseClicked
       Registro_usuario  ru = new Registro_usuario();
        ru.setVisible(true);
        ru.pack();
        ru.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_registroMouseClicked
    
    
    
    
    
    
                                          

                                            

                                         

                                           

               
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_usuario_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_usuario_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_usuario_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_usuario_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_usuario_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_Close2;
    private javax.swing.JLabel jLabel_Minimize1;
    private javax.swing.JLabel jLabel_direciona_farmaceutico;
    private javax.swing.JLabel jLabel_login;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_registro;
    private javax.swing.JLabel jLabel_titulo_usuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
